//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string credit_number { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<decimal> withdrow { get; set; }
        public Nullable<int> bank_id { get; set; }
    
        public virtual Bank Bank { get; set; }
    }
}
